### PR TITLE
Issue/28 rest api version

### LINKED ISSUE #28: Bump wpcom REST API version to 1.1
Title has it. 
Refs https://github.com/wordpress-mobile/WordPress-iOS/issues/2989

### PR DESCRIPTION
**Pull request by aerych**
Closes #28

### CODE REVIEW

**Comment by aerych** [comment]
cc @SergioEstevao for review

**Comment by aerych** [comment]
Note to self... remember to tag release after merging :)

**Comment by aerych** [comment]
> Maybe this update deserves an 0.3 version

Sounded good to me :)

**Comment by SergioEstevao** [comment]
:shipit:

**Pull request merged**
